
from typing import Any, Dict, Optional, Literal, List, Callable
from pydantic import BaseModel, Field, ConfigDict, field_validator, ValidationError

class PlannerStateUpdate(BaseModel):
    """Fields the planner may change. Pass only the keys you want to modify."""
    model_config = ConfigDict(extra='forbid')
    
    intent: Optional[Literal['SQL_ONLY','SQL_AND_VIZ','CLARITY']] = Field(
        default=None,
        description="Intent extracted from the current user query."
    )
    viz_requested: Optional[Literal['bar_chart','line_chart','pie_chart','table','none']] = Field(
        default=None,
        description="Visualization type requested by the user."
    )
    clarifying_question: Optional[str] = Field(
        default=None,
        description="Set ONLY if the query is ambiguous or missing required info."
    )
    assumptions: Optional[str] = Field(default=None,
        description="Assumptions to carry into SQL generation."
    )
    user_session_summary: Optional[str] = Field(
        default=None,
        description="Compact running summary of the conversation."
    )
    last_invocation_query: Optional[str] = Field(
        default=None,
        description="Previous user query."
    )
    table_schema_artifact: Optional[str] = Field(
        default=None,
        description="Artifact Id of table schema in database."
    )
    last_validated_sql: Optional[str] = Field(
        default=None,
        description="Final validated SQL query generated by SQL_SPECIALIST tool."
    )
    final_query_status: Optional[Literal['SUCCESS','FAIL_NEEDS_CLARIFICATION','FAIL_MAX_RETRIES']] = Field(
        default=None,
        description='Status of generated SQL query form SQL specialist agent'
    )
    viz_status: Optional[Literal['SUCCESS','FAIL_MAX_RETRIES','NOT_GENERATED']] = Field(
        default = None,
        description = "Status of visualization agent."
    )
    viz_artifact: Optional[str] = Field(
        default = None, 
        description = "Artifact ID generated by visualization agent"
    )
















# class MainRouter(BaseModel):
#     model_config = ConfigDict(extra='ignore')

#     intent: Literal['SQL_ONLY', 'SQL_AND_VIZ', 'CLARITY'] = Field(
#         default = 'SQL_ONLY',
#         description="Intent Extracted from current user query."
#     )
#     last_validated_sql: Optional[str] = Field(
#         default=None,
#         description="Final validated SQL query generated by SQL_SPECIALIST tool."
#     )
#     table_schema_artifact: str = Field(
#         description="Artifact Id of table schema in database."
#     )
#     current_invocation_query: str = Field(
#         description="Latest user query. MUST always contain the current user input."
#     )
#     last_invocation_query: Optional[str] = Field(
#         default=None,
#         description="Previous user query."
#     )
#     user_session_summary: Optional[str] = Field(
#         default=None,
#         description="Compact summary of entire conversation so far."
#     )
#     viz_requested: Optional[Literal["bar_chart", "line_chart", "pie_chart", "table", "none"]] = Field(
#         default=None,
#         description="Type of visualization requested by user."
#     )
#     clarifying_question: Optional[str] = Field(
#         default=None,
#         description="Ask a question ONLY if user query is ambiguous or missing required info."
#     )
#     MAX_RETRIES: int = 3
#     MAX_VIZ_RETRIES: int = 3
#     assumptions: Optional[str] = Field(
#         default = None, 
#         description = "Assumptions for final generated SQL query"
#     )
#     final_query_status: Optional[Literal['SUCCESS', 'FAIL_NEEDS_CLARIFICATION', 'FAIL_MAX_RETRIES']] = Field(
#         default = None,
#         description = 'Status of generated SQL query form SQL specialist agent'
#     )
#     VIZ_STATUS: Literal['SUCCESS', 'FAIL_MAX_RETRIES', 'NOT_GENERATED'] = Field(
#         default = 'NOT_GENERATED',
#         description = "Status of visualization agent."
#     )
#     VIZ_artifact: Optional[str] = Field(
#         default = None, 
#         description = "Artifact ID generated by visualization agent"
#     )