from pydantic import BaseModel, Field, ConfigDict
from typing import Literal, Optional

class MainRouter(BaseModel):
    model_config = ConfigDict(extra='ignore')

    intent: Literal['SQL_ONLY', 'SQL_AND_VIZ', 'CLARITY'] = Field(
        description="Intent Extracted from current user query."
    )
    last_validated_sql: Optional[str] = Field(
        default=None,
        description="Final validated SQL query generated by SQL_SPECIALIST tool."
    )
    table_schema_artifact: str = Field(
        description="Artifact Id of table schema in database."
    )
    current_invocation_query: str = Field(
        description="Latest user query. MUST always contain the current user input."
    )
    last_invocation_query: Optional[str] = Field(
        default=None,
        description="Previous user query."
    )
    user_session_summary: Optional[str] = Field(
        default=None,
        description="Compact summary of entire conversation so far."
    )
    viz_requested: Optional[Literal["bar_chart", "line_chart", "pie_chart", "table", "none"]] = Field(
        default="none",
        description="Type of visualization requested by user."
    )
    clarifying_question: Optional[str] = Field(
        default=None,
        description="Ask a question ONLY if user query is ambiguous or missing required info."
    )
    MAX_RETRIES: int = 3
    MAX_VIZ_RETRIES: int = 3
    assumptions: Optional[str] = Field(
        default=None, 
        description="Assumptions for final generated SQL query"
    )
    final_query_status: Literal['SUCCESS', 'FAIL_NEEDS_CLARIFICATION', 'FAIL_MAX_RETRIES'] = Field(
        default=None,
        description='Status of generated SQL query'
    )
    VIZ_STATUS: Literal['SUCCESS', 'FAIL_MAX_RETRIES'] = Field(
        default=None,
        description="Status of visualization agent"
    )
    VIZ_artifact: Optional[str] = Field(
        default=None, 
        description="Artifact ID of visualization."
    )